name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.1, 8.0, 7.4]
        laravel: [10.*, 9.*, 8.*, 7.*, 6.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*
            carbon: ^2.63
            ramsey: ^4.7
            phpunit: ^10.1
          - laravel: 9.*
            testbench: ^7.24
            carbon: ^2.62.1
            ramsey: ^4.7
            phpunit: ^9.0
          - laravel: 8.*
            testbench: ^6.27
            carbon: ^2.53.1
            ramsey: ^4.7
            phpunit: ^8.0
          - laravel: 7.*
            testbench: ^5.8
            carbon: ^2.31
            ramsey: ^3.0
            phpunit: ^8.0
          - laravel: 6.*
            testbench: 4.*
            carbon: ^2.31
            ramsey: ^3.0
            phpunit: ^8.0
        exclude:
          - laravel: 10.*
            php: 8.0
          - laravel: 10.*
            php: 7.4
          - laravel: 9.*
            php: 7.4
          - laravel: 8.*
            php: 8.2
          - laravel: 8.*
            php: 8.1
          - laravel: 8.*
            php: 7.4
          - laravel: 7.*
            php: 8.2
          - laravel: 7.*
            php: 8.1
          - laravel: 6.*
            php: 8.2
          - laravel: 6.*
            php: 8.1
          - laravel: 6.*
            php: 8.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" "ramsey/uuid:${{ matrix.ramsey }}" --no-interaction --no-update
          composer require "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update --dev
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/phpunit
